/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppBillBillIdIndexRouteImport } from './routes/app.bill.$billId.index'
import { Route as AppBillBillIdVoteRouteImport } from './routes/app.bill.$billId.vote'
import { Route as AppBillBillIdTotalsRouteImport } from './routes/app.bill.$billId.totals'
import { Route as AppBillBillIdItemsIndexRouteImport } from './routes/app.bill.$billId.items.index'
import { Route as AppBillBillIdItemsItemIdRouteImport } from './routes/app.bill.$billId.items.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillBillIdIndexRoute = AppBillBillIdIndexRouteImport.update({
  id: '/app/bill/$billId/',
  path: '/app/bill/$billId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillBillIdVoteRoute = AppBillBillIdVoteRouteImport.update({
  id: '/app/bill/$billId/vote',
  path: '/app/bill/$billId/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillBillIdTotalsRoute = AppBillBillIdTotalsRouteImport.update({
  id: '/app/bill/$billId/totals',
  path: '/app/bill/$billId/totals',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillBillIdItemsIndexRoute = AppBillBillIdItemsIndexRouteImport.update({
  id: '/app/bill/$billId/items/',
  path: '/app/bill/$billId/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillBillIdItemsItemIdRoute =
  AppBillBillIdItemsItemIdRouteImport.update({
    id: '/app/bill/$billId/items/$itemId',
    path: '/app/bill/$billId/items/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/bill/$billId/totals': typeof AppBillBillIdTotalsRoute
  '/app/bill/$billId/vote': typeof AppBillBillIdVoteRoute
  '/app/bill/$billId': typeof AppBillBillIdIndexRoute
  '/app/bill/$billId/items/$itemId': typeof AppBillBillIdItemsItemIdRoute
  '/app/bill/$billId/items': typeof AppBillBillIdItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bill/$billId/totals': typeof AppBillBillIdTotalsRoute
  '/app/bill/$billId/vote': typeof AppBillBillIdVoteRoute
  '/app/bill/$billId': typeof AppBillBillIdIndexRoute
  '/app/bill/$billId/items/$itemId': typeof AppBillBillIdItemsItemIdRoute
  '/app/bill/$billId/items': typeof AppBillBillIdItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/bill/$billId/totals': typeof AppBillBillIdTotalsRoute
  '/app/bill/$billId/vote': typeof AppBillBillIdVoteRoute
  '/app/bill/$billId/': typeof AppBillBillIdIndexRoute
  '/app/bill/$billId/items/$itemId': typeof AppBillBillIdItemsItemIdRoute
  '/app/bill/$billId/items/': typeof AppBillBillIdItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/bill/$billId/totals'
    | '/app/bill/$billId/vote'
    | '/app/bill/$billId'
    | '/app/bill/$billId/items/$itemId'
    | '/app/bill/$billId/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bill/$billId/totals'
    | '/app/bill/$billId/vote'
    | '/app/bill/$billId'
    | '/app/bill/$billId/items/$itemId'
    | '/app/bill/$billId/items'
  id:
    | '__root__'
    | '/'
    | '/app/bill/$billId/totals'
    | '/app/bill/$billId/vote'
    | '/app/bill/$billId/'
    | '/app/bill/$billId/items/$itemId'
    | '/app/bill/$billId/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppBillBillIdTotalsRoute: typeof AppBillBillIdTotalsRoute
  AppBillBillIdVoteRoute: typeof AppBillBillIdVoteRoute
  AppBillBillIdIndexRoute: typeof AppBillBillIdIndexRoute
  AppBillBillIdItemsItemIdRoute: typeof AppBillBillIdItemsItemIdRoute
  AppBillBillIdItemsIndexRoute: typeof AppBillBillIdItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bill/$billId/': {
      id: '/app/bill/$billId/'
      path: '/app/bill/$billId'
      fullPath: '/app/bill/$billId'
      preLoaderRoute: typeof AppBillBillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bill/$billId/vote': {
      id: '/app/bill/$billId/vote'
      path: '/app/bill/$billId/vote'
      fullPath: '/app/bill/$billId/vote'
      preLoaderRoute: typeof AppBillBillIdVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bill/$billId/totals': {
      id: '/app/bill/$billId/totals'
      path: '/app/bill/$billId/totals'
      fullPath: '/app/bill/$billId/totals'
      preLoaderRoute: typeof AppBillBillIdTotalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bill/$billId/items/': {
      id: '/app/bill/$billId/items/'
      path: '/app/bill/$billId/items'
      fullPath: '/app/bill/$billId/items'
      preLoaderRoute: typeof AppBillBillIdItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bill/$billId/items/$itemId': {
      id: '/app/bill/$billId/items/$itemId'
      path: '/app/bill/$billId/items/$itemId'
      fullPath: '/app/bill/$billId/items/$itemId'
      preLoaderRoute: typeof AppBillBillIdItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppBillBillIdTotalsRoute: AppBillBillIdTotalsRoute,
  AppBillBillIdVoteRoute: AppBillBillIdVoteRoute,
  AppBillBillIdIndexRoute: AppBillBillIdIndexRoute,
  AppBillBillIdItemsItemIdRoute: AppBillBillIdItemsItemIdRoute,
  AppBillBillIdItemsIndexRoute: AppBillBillIdItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
