/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppBillChatIdMessageIdIndexImport } from './routes/app.bill.$chatId.$messageId.index'
import { Route as AppBillChatIdMessageIdSummaryImport } from './routes/app.bill.$chatId.$messageId.summary'
import { Route as AppBillChatIdMessageIdResultsImport } from './routes/app.bill.$chatId.$messageId.results'
import { Route as AppBillChatIdMessageIdItemItemIdImport } from './routes/app.bill.$chatId.$messageId.item.$itemId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppBillChatIdMessageIdIndexRoute =
  AppBillChatIdMessageIdIndexImport.update({
    id: '/app/bill/$chatId/$messageId/',
    path: '/app/bill/$chatId/$messageId/',
    getParentRoute: () => rootRoute,
  } as any)

const AppBillChatIdMessageIdSummaryRoute =
  AppBillChatIdMessageIdSummaryImport.update({
    id: '/app/bill/$chatId/$messageId/summary',
    path: '/app/bill/$chatId/$messageId/summary',
    getParentRoute: () => rootRoute,
  } as any)

const AppBillChatIdMessageIdResultsRoute =
  AppBillChatIdMessageIdResultsImport.update({
    id: '/app/bill/$chatId/$messageId/results',
    path: '/app/bill/$chatId/$messageId/results',
    getParentRoute: () => rootRoute,
  } as any)

const AppBillChatIdMessageIdItemItemIdRoute =
  AppBillChatIdMessageIdItemItemIdImport.update({
    id: '/app/bill/$chatId/$messageId/item/$itemId',
    path: '/app/bill/$chatId/$messageId/item/$itemId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/bill/$chatId/$messageId/results': {
      id: '/app/bill/$chatId/$messageId/results'
      path: '/app/bill/$chatId/$messageId/results'
      fullPath: '/app/bill/$chatId/$messageId/results'
      preLoaderRoute: typeof AppBillChatIdMessageIdResultsImport
      parentRoute: typeof rootRoute
    }
    '/app/bill/$chatId/$messageId/summary': {
      id: '/app/bill/$chatId/$messageId/summary'
      path: '/app/bill/$chatId/$messageId/summary'
      fullPath: '/app/bill/$chatId/$messageId/summary'
      preLoaderRoute: typeof AppBillChatIdMessageIdSummaryImport
      parentRoute: typeof rootRoute
    }
    '/app/bill/$chatId/$messageId/': {
      id: '/app/bill/$chatId/$messageId/'
      path: '/app/bill/$chatId/$messageId'
      fullPath: '/app/bill/$chatId/$messageId'
      preLoaderRoute: typeof AppBillChatIdMessageIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/bill/$chatId/$messageId/item/$itemId': {
      id: '/app/bill/$chatId/$messageId/item/$itemId'
      path: '/app/bill/$chatId/$messageId/item/$itemId'
      fullPath: '/app/bill/$chatId/$messageId/item/$itemId'
      preLoaderRoute: typeof AppBillChatIdMessageIdItemItemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/bill/$chatId/$messageId/results': typeof AppBillChatIdMessageIdResultsRoute
  '/app/bill/$chatId/$messageId/summary': typeof AppBillChatIdMessageIdSummaryRoute
  '/app/bill/$chatId/$messageId': typeof AppBillChatIdMessageIdIndexRoute
  '/app/bill/$chatId/$messageId/item/$itemId': typeof AppBillChatIdMessageIdItemItemIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bill/$chatId/$messageId/results': typeof AppBillChatIdMessageIdResultsRoute
  '/app/bill/$chatId/$messageId/summary': typeof AppBillChatIdMessageIdSummaryRoute
  '/app/bill/$chatId/$messageId': typeof AppBillChatIdMessageIdIndexRoute
  '/app/bill/$chatId/$messageId/item/$itemId': typeof AppBillChatIdMessageIdItemItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/bill/$chatId/$messageId/results': typeof AppBillChatIdMessageIdResultsRoute
  '/app/bill/$chatId/$messageId/summary': typeof AppBillChatIdMessageIdSummaryRoute
  '/app/bill/$chatId/$messageId/': typeof AppBillChatIdMessageIdIndexRoute
  '/app/bill/$chatId/$messageId/item/$itemId': typeof AppBillChatIdMessageIdItemItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/bill/$chatId/$messageId/results'
    | '/app/bill/$chatId/$messageId/summary'
    | '/app/bill/$chatId/$messageId'
    | '/app/bill/$chatId/$messageId/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bill/$chatId/$messageId/results'
    | '/app/bill/$chatId/$messageId/summary'
    | '/app/bill/$chatId/$messageId'
    | '/app/bill/$chatId/$messageId/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/app/bill/$chatId/$messageId/results'
    | '/app/bill/$chatId/$messageId/summary'
    | '/app/bill/$chatId/$messageId/'
    | '/app/bill/$chatId/$messageId/item/$itemId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppBillChatIdMessageIdResultsRoute: typeof AppBillChatIdMessageIdResultsRoute
  AppBillChatIdMessageIdSummaryRoute: typeof AppBillChatIdMessageIdSummaryRoute
  AppBillChatIdMessageIdIndexRoute: typeof AppBillChatIdMessageIdIndexRoute
  AppBillChatIdMessageIdItemItemIdRoute: typeof AppBillChatIdMessageIdItemItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppBillChatIdMessageIdResultsRoute: AppBillChatIdMessageIdResultsRoute,
  AppBillChatIdMessageIdSummaryRoute: AppBillChatIdMessageIdSummaryRoute,
  AppBillChatIdMessageIdIndexRoute: AppBillChatIdMessageIdIndexRoute,
  AppBillChatIdMessageIdItemItemIdRoute: AppBillChatIdMessageIdItemItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/bill/$chatId/$messageId/results",
        "/app/bill/$chatId/$messageId/summary",
        "/app/bill/$chatId/$messageId/",
        "/app/bill/$chatId/$messageId/item/$itemId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/bill/$chatId/$messageId/results": {
      "filePath": "app.bill.$chatId.$messageId.results.tsx"
    },
    "/app/bill/$chatId/$messageId/summary": {
      "filePath": "app.bill.$chatId.$messageId.summary.tsx"
    },
    "/app/bill/$chatId/$messageId/": {
      "filePath": "app.bill.$chatId.$messageId.index.tsx"
    },
    "/app/bill/$chatId/$messageId/item/$itemId": {
      "filePath": "app.bill.$chatId.$messageId.item.$itemId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
